### ISSUE TITLE
Wipe Engine Starts, Nothing Happens

### ISSUE THREAD

**Issue by guyintruck** [guyintruck/RedWipe#3]
Several users have noted that the program is now stalling on their machines.  Will look into.

**Comment by therandomjoe** [comment]
How this happens:

1. Log into your username.
2. Click on "Wipe".
3. Accept warning message.
4. The number of posts and comments will show on the console log.
5. After some time passes (during which the program doesn't delete any post/comment), it'll crash.

**Comment by anonymousvibrations** [comment]
Hi,

I'm having the same issue as therandomjoe. Says "Logged in as...", then says "Wipe engine loading", followed by the number of posts and comments being listed once. Nothing happens from here, it hasn't crashed yet but maybe I haven't left it long enough, though it has been left a while. Have restarted, reinstalled. Trying to load the exe once it has been installed yields an exception error. Have to reinstall for it to work again.

**Comment by guyintruck** [comment]
Try running it again only this time after it appears to freeze click "cancel". I would like to know if that works.  I cannot recreate this issues on my machine.

**Comment by therandomjoe** [comment]
Do you mean pressing "Stop!"?

When I do that after accepting to wipe my account it seems to stop/do nothing. If I press "Wipe my account", no matter if it's active already or if I have pressed "Stop!" beforehand, I get the confirmation warning and a text that says "Wipe engine loading..."

Only the first time I press "Wipe my account" it shows my # of posts and comments, afterwards just the "Wipe engine loading..." message.

It still doesn't work.

**Comment by anonymousvibrations** [comment]
Pressing "Stop!" didn't appear to have any effect. I left it for a bit and still nothing. Tried "Wipe My Account" again, but it didn't get past "Wipe Engine Loading...". I then clicked "Login" again, at which point the application completely froze, getting the not responding Windows error and had to close it.

**Comment by guyintruck** [comment]
Thank you for letting me know this.  For now I would look for another
solution until I can get this fixed.  Expecting my first child in a few
weeks, so I'm very busy.

Thanks again!!

**Comment by therandomjoe** [comment]
Congratulations, guyintruck :)

**Comment by anonymousvibrations** [comment]
No worries :) congrats on the little one. I got it working. Apparently if I was logged in in the browser it refused to work. However, it would only delete two at a time, and then stop. I tried it again today and it worked! It deleted 27 posts before crashing. Nevermind, it wasn't the program's fault that it crashed, my net dropped out which caused the crash.Crashed again after deleting 76 posts, this time not due to connectivity issues that I saw. The remaining posts deleted without issue.

**Comment by guyintruck** [comment]
I believe this has been fixed.

**Comment by anonymousvibrations** [comment]
Thank you :) great program.

**Comment by raufguliev** [comment]
I have the same issue right now. After logging in and clicking on Wipe My Account, and accepting the popup about the last 1000 comments it just stays on Wipe engine loading...

Clicking on stop does nothing, the only way to stop it is to shut down the program. Is there anything I can do?

**Comment by McNippleson** [comment]
Same. This was happening in Win 8.1 and now in Win 10.

**Comment by guyintruck** [comment]
These issues seem to have been related to the estimated time of completion part of the program.. This has been removed.
