### ISSUE TITLE
Consistently crashes after ~25 deletes.

### ISSUE THREAD

**Issue by xanat0s** [guyintruck/RedWipe#4]
RedWipe has crashed for the 6th time in a row, throwing an unhandled exception. It always occurs after (roughly) 25 successful deletes.

Here is the exception:

`System.Net.WebException was unhandled`
`Message: An unhandled exception of type 'System.Net.WebException' occurred in System.dll`
`Additional information: The remote server returned an error: (504) Gateway Timeout.`

I don't have the time to look into it myself, I'm sorry. I'm running Win10 build 10240, if that's helpful.

**Comment by guyintruck** [comment]
RedWipe was loosing connection with the server.  This may be related to the estimated time of completion issue.  Which I believe has been fixed.
